packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@sentry/cli': true
  core-js: true
  esbuild: true
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@sentry/cli'
  - core-js
  - sharp
  - '@parcel/watcher'
  - '@swc/core'
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - protobufjs
  - unrs-resolver
