services:
  - type: web
    name: platform-api
    runtime: docker
    dockerfilePath: ./infra/docker/Dockerfile.runtime
    dockerContext: .
    healthCheckPath: /health/live
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:8080
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: Redis__Configuration
        sync: false
      - key: Jwt__Secret
        sync: false
      - key: Jwt__SigningKeySecret
        sync: false
      - key: Cors__AllowedOrigins
        sync: false

  - type: worker
    name: platform-judge
    runtime: docker
    dockerfilePath: ./infra/docker/Dockerfile.runtime
    dockerContext: .
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: Redis__Configuration
        sync: false
      - key: APP_DLL
        value: Platform.Judge.dll
