export const ROUTES = {
  PUBLIC: {
    HOME: '/',
    COURSES: '/courses',
    COURSE_DETAIL: (id: number | string) => `/courses/${id}`,
    PRICING: '/pricing',
  },
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    VERIFY_EMAIL: '/auth/verify-email',
    TWO_FACTOR: '/auth/2fa',
  },
  STUDENT: {
    DASHBOARD: '/dashboard',
    LEARN: (courseId: number | string) => `/learn/${courseId}`,
    EXAM: (courseId: number | string, examId: number | string) => `/learn/${courseId}/exam/${examId}`,
    HOMEWORK: (courseId: number | string, homeworkId: number | string) => `/learn/${courseId}/homework/${homeworkId}`,
    JUDGE: '/judge',
    JUDGE_CHALLENGE: (id: number | string) => `/judge/${id}`,
    LIVE_SESSIONS: '/live',
    LIVE_SESSION: (id: number | string) => `/live/${id}`,
    NOTIFICATIONS: '/notifications',
    PROFILE: '/profile',
    SETTINGS: '/settings',
    BILLING: '/billing',
  },
  TEACHER: {
    DASHBOARD: '/teacher/dashboard',
    COURSES: '/teacher/courses',
    CREATE_COURSE: '/teacher/courses/new',
    EDIT_COURSE: (id: number | string) => `/teacher/courses/${id}/edit`,
    MANAGE_MODULES: (id: number | string) => `/teacher/courses/${id}/modules`,
  },
  CHECKOUT: {
    INDEX: '/checkout',
    SUCCESS: '/checkout/success',
    FAILED: '/checkout/failed',
    PENDING: '/checkout/pending',
  },
  ADMIN: {
    DASHBOARD: '/',
    USERS: '/users',
    COURSES: '/courses',
    AUDIT_LOGS: '/audit-logs',
    SUBSCRIPTIONS: '/subscriptions',
  },
} as const;
