// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class AdminProfile
{
    public long UserId { get; set; }

    public string Department { get; set; }

    public string AccessLevel { get; set; }

    public string Notes { get; set; }

    public virtual User User { get; set; }
}