// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class AnalyticsSnapshot
{
    public long Id { get; set; }

    public string MetricName { get; set; }

    public decimal MetricValue { get; set; }

    public string Dimension { get; set; }

    public DateTime RecordedAt { get; set; }
}