// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class Announcement
{
    public long Id { get; set; }

    public long TeacherId { get; set; }

    public long? CourseId { get; set; }

    public string Title { get; set; }

    public string Body { get; set; }

    public DateTime PublishedAt { get; set; }

    public bool IsPinned { get; set; }

    public virtual Course Course { get; set; }

    public virtual TeacherProfile Teacher { get; set; }
}