// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class ApiKey
{
    public long Id { get; set; }

    public string Name { get; set; }

    public string KeyValue { get; set; }

    public string Provider { get; set; }

    public string Scope { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? ExpiresAt { get; set; }

    public bool IsActive { get; set; }
}