// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class BackgroundJob
{
    public long Id { get; set; }

    public string JobType { get; set; }

    public string JobData { get; set; }

    public string Status { get; set; }

    public DateTime ScheduledAt { get; set; }

    public DateTime? ExecutedAt { get; set; }

    public string Result { get; set; }
}