// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class Certificate
{
    public long Id { get; set; }

    public long StudentId { get; set; }

    public long? CourseId { get; set; }

    public long? ExamId { get; set; }

    public string CertificateNumber { get; set; }

    public DateTime IssuedAt { get; set; }

    public string FileUrl { get; set; }

    public virtual Course Course { get; set; }

    public virtual Exam Exam { get; set; }

    public virtual StudentProfile Student { get; set; }
}