// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class CodingChallenge
{
    public long Id { get; set; }

    public long TeacherId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Language { get; set; }

    public string StarterCode { get; set; }

    public string TestCases { get; set; }

    public string Difficulty { get; set; }

    public decimal Marks { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<CodingSubmission> CodingSubmissions { get; set; } = new List<CodingSubmission>();

    public virtual TeacherProfile Teacher { get; set; }
}