// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class CodingSubmission
{
    public long Id { get; set; }

    public long CodingChallengeId { get; set; }

    public long StudentId { get; set; }

    public string SourceCode { get; set; }

    public string FileUrl { get; set; }

    public DateTime SubmittedAt { get; set; }

    public decimal? Score { get; set; }

    public string Status { get; set; }

    public string ExecutionResult { get; set; }

    public virtual CodingChallenge CodingChallenge { get; set; }

    public virtual StudentProfile Student { get; set; }
}