// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class CourseModule
{
    public long Id { get; set; }

    public long CourseId { get; set; }

    public string Title { get; set; }

    public int MonthNumber { get; set; }

    public int Order { get; set; }

    public string Description { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Course Course { get; set; }

    public virtual ICollection<Lesson> Lessons { get; set; } = new List<Lesson>();

    public virtual ICollection<LiveSession> LiveSessions { get; set; } = new List<LiveSession>();
}