// <auto-generated> Course enrollment aggregate persisted in the platform database. </auto-generated>
#nullable disable
using System;

namespace Platform.Domain.Entities;

public partial class CourseEnrollment
{
    public long Id { get; set; }

    public long CourseId { get; set; }

    public long StudentId { get; set; }

    public string Status { get; set; }

    public string AccessType { get; set; }

    public long? PaymentId { get; set; }

    public DateTime EnrolledAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public virtual Course Course { get; set; }

    public virtual Payment Payment { get; set; }

    public virtual StudentProfile Student { get; set; }
}
