// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class ExamResult
{
    public long Id { get; set; }

    public long ExamAttemptId { get; set; }

    public long StudentId { get; set; }

    public long ExamId { get; set; }

    public decimal TotalScore { get; set; }

    public decimal Percentage { get; set; }

    public string Grade { get; set; }

    public bool PassedStatus { get; set; }

    public DateTime GeneratedAt { get; set; }

    public virtual Exam Exam { get; set; }

    public virtual ExamAttempt ExamAttempt { get; set; }

    public virtual StudentProfile Student { get; set; }
}