// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class ExamQuestion
{
    public long Id { get; set; }

    public long ExamId { get; set; }

    public long QuestionId { get; set; }

    public int Order { get; set; }

    public decimal Marks { get; set; }

    public virtual Exam Exam { get; set; }

    public virtual Question Question { get; set; }
}