// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class ExamAnswer
{
    public long Id { get; set; }

    public long ExamAttemptId { get; set; }

    public long QuestionId { get; set; }

    public string AnswerText { get; set; }

    public string SelectedChoiceIds { get; set; }

    public bool? IsCorrect { get; set; }

    public decimal? MarksObtained { get; set; }

    public virtual ExamAttempt ExamAttempt { get; set; }

    public virtual Question Question { get; set; }
}