// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class ExamAttempt
{
    public long Id { get; set; }

    public long ExamId { get; set; }

    public long StudentId { get; set; }

    public DateTime StartedAt { get; set; }

    public DateTime? SubmittedAt { get; set; }

    public string Status { get; set; }

    public decimal? Score { get; set; }

    public virtual Exam Exam { get; set; }

    public virtual ICollection<ExamAnswer> ExamAnswers { get; set; } = new List<ExamAnswer>();

    public virtual ExamResult ExamResult { get; set; }

    public virtual StudentProfile Student { get; set; }
}