// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class Exam
{
    public long Id { get; set; }

    public long TeacherId { get; set; }

    public long? CourseId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int DurationMinutes { get; set; }

    public decimal TotalMarks { get; set; }

    public decimal? PassingMarks { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public bool IsPublished { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Certificate> Certificates { get; set; } = new List<Certificate>();

    public virtual Course Course { get; set; }

    public virtual ICollection<ExamAttempt> ExamAttempts { get; set; } = new List<ExamAttempt>();

    public virtual ICollection<ExamQuestion> ExamQuestions { get; set; } = new List<ExamQuestion>();

    public virtual ICollection<ExamResult> ExamResults { get; set; } = new List<ExamResult>();

    public virtual TeacherProfile Teacher { get; set; }
}