// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class File
{
    public long Id { get; set; }

    public long UploaderId { get; set; }

    public string FileName { get; set; }

    public string FileUrl { get; set; }

    public string FileType { get; set; }

    public long? FileSizeBytes { get; set; }

    public string EntityType { get; set; }

    public long? EntityId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual User Uploader { get; set; }
}