// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class Homework
{
    public long Id { get; set; }

    public long TeacherId { get; set; }

    public long? CourseId { get; set; }

    public long? LessonId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public DateTime? DueDate { get; set; }

    public decimal TotalMarks { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Course Course { get; set; }

    public virtual ICollection<HomeworkQuestion> HomeworkQuestions { get; set; } = new List<HomeworkQuestion>();

    public virtual ICollection<HomeworkSubmission> HomeworkSubmissions { get; set; } = new List<HomeworkSubmission>();

    public virtual Lesson Lesson { get; set; }

    public virtual TeacherProfile Teacher { get; set; }
}