// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class HomeworkSubmission
{
    public long Id { get; set; }

    public long HomeworkId { get; set; }

    public long StudentId { get; set; }

    public string SubmissionType { get; set; }

    public string FileUrl { get; set; }

    public string TextAnswer { get; set; }

    public DateTime SubmittedAt { get; set; }

    public decimal? Grade { get; set; }

    public string Feedback { get; set; }

    public string Status { get; set; }

    public virtual Homework Homework { get; set; }

    public virtual StudentProfile Student { get; set; }
}