// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class ImportedPackage
{
    public long Id { get; set; }

    public long TeacherId { get; set; }

    public string PackageVersion { get; set; }

    public string AIProvider { get; set; }

    public DateTime ImportDate { get; set; }

    public string Status { get; set; }

    public virtual ICollection<ImportLog> ImportLogs { get; set; } = new List<ImportLog>();

    public virtual ICollection<ImportedLesson> ImportedLessons { get; set; } = new List<ImportedLesson>();

    public virtual ICollection<ImportedQuestionBank> ImportedQuestionBanks { get; set; } = new List<ImportedQuestionBank>();

    public virtual TeacherProfile Teacher { get; set; }
}