// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class ImportedLesson
{
    public long Id { get; set; }

    public long ImportedPackageId { get; set; }

    public string LessonMarkdown { get; set; }

    public long? TargetLessonId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ImportedPackage ImportedPackage { get; set; }

    public virtual Lesson TargetLesson { get; set; }
}