// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class ImportLog
{
    public long Id { get; set; }

    public long ImportedPackageId { get; set; }

    public string LogLevel { get; set; }

    public string Message { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ImportedPackage ImportedPackage { get; set; }
}