// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class LessonResource
{
    public long Id { get; set; }

    public long LessonId { get; set; }

    public string ResourceType { get; set; }

    public string FileUrl { get; set; }

    public string FileName { get; set; }

    public long? FileSizeBytes { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Lesson Lesson { get; set; }
}