// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class LessonVideo
{
    public long Id { get; set; }

    public long LessonId { get; set; }

    public string VideoUrl { get; set; }

    public string RecordingUrl { get; set; }

    public int? Duration { get; set; }

    public string Provider { get; set; }

    public string Thumbnail { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Lesson Lesson { get; set; }
}