// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class Lesson
{
    public long Id { get; set; }

    public long ModuleId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int? Duration { get; set; }

    public int Order { get; set; }

    public bool IsPublished { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<Homework> Homeworks { get; set; } = new List<Homework>();

    public virtual ICollection<ImportedLesson> ImportedLessons { get; set; } = new List<ImportedLesson>();

    public virtual ICollection<LessonResource> LessonResources { get; set; } = new List<LessonResource>();

    public virtual ICollection<LessonVideo> LessonVideos { get; set; } = new List<LessonVideo>();

    public virtual CourseModule Module { get; set; }

    public virtual ICollection<StudentProgress> StudentProgresses { get; set; } = new List<StudentProgress>();
}