// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class LiveSession
{
    public long Id { get; set; }

    public long TeacherId { get; set; }

    public long? CourseId { get; set; }

    public long? ModuleId { get; set; }

    public int ProviderId { get; set; }

    public string Title { get; set; }

    public string MeetingId { get; set; }

    public string MeetingLink { get; set; }

    public string Password { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public string RecordingLink { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Course Course { get; set; }

    public virtual ICollection<LiveAttendance> LiveAttendances { get; set; } = new List<LiveAttendance>();

    public virtual CourseModule Module { get; set; }

    public virtual LiveMeetingProvider Provider { get; set; }

    public virtual TeacherProfile Teacher { get; set; }
}