// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class LiveAttendance
{
    public long Id { get; set; }

    public long LiveSessionId { get; set; }

    public long StudentId { get; set; }

    public DateTime? JoinTime { get; set; }

    public DateTime? LeaveTime { get; set; }

    public int? DurationSeconds { get; set; }

    public virtual LiveSession LiveSession { get; set; }

    public virtual StudentProfile Student { get; set; }
}