// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class NotificationHistory
{
    public long Id { get; set; }

    public long? NotificationId { get; set; }

    public long UserId { get; set; }

    public string Channel { get; set; }

    public string Status { get; set; }

    public DateTime SentAt { get; set; }

    public virtual Notification Notification { get; set; }

    public virtual User User { get; set; }
}