// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class Notification
{
    public long Id { get; set; }

    public long UserId { get; set; }

    public string Title { get; set; }

    public string Body { get; set; }

    public string Type { get; set; }

    public bool IsRead { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<NotificationHistory> NotificationHistories { get; set; } = new List<NotificationHistory>();

    public virtual User User { get; set; }
}