// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class ParentNotification
{
    public long Id { get; set; }

    public long StudentId { get; set; }

    public string ParentPhone { get; set; }

    public string ReportType { get; set; }

    public string ReportContent { get; set; }

    public DateTime SentAt { get; set; }

    public virtual StudentProfile Student { get; set; }
}