// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class Payment
{
    public long Id { get; set; }

    public long StudentId { get; set; }

    public long? SubscriptionId { get; set; }

    public string TransactionId { get; set; }

    public decimal Amount { get; set; }

    public string Currency { get; set; }

    public string Status { get; set; }

    public string PaymentMethod { get; set; }

    public DateTime? PaidAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Invoice Invoice { get; set; }

    public virtual StudentProfile Student { get; set; }

    public virtual StudentSubscription Subscription { get; set; }
}