// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class Question
{
    public long Id { get; set; }

    public long QuestionBankId { get; set; }

    public int QuestionTypeId { get; set; }

    public string Body { get; set; }

    public string Difficulty { get; set; }

    public string Skill { get; set; }

    public string BloomLevel { get; set; }

    public int? EstimatedTimeSeconds { get; set; }

    public decimal Marks { get; set; }

    public string Explanation { get; set; }

    public string Metadata { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<ExamAnswer> ExamAnswers { get; set; } = new List<ExamAnswer>();

    public virtual ICollection<ExamQuestion> ExamQuestions { get; set; } = new List<ExamQuestion>();

    public virtual ICollection<HomeworkQuestion> HomeworkQuestions { get; set; } = new List<HomeworkQuestion>();

    public virtual ICollection<QuestionAttachment> QuestionAttachments { get; set; } = new List<QuestionAttachment>();

    public virtual QuestionBank QuestionBank { get; set; }

    public virtual ICollection<QuestionChoice> QuestionChoices { get; set; } = new List<QuestionChoice>();

    public virtual QuestionType QuestionType { get; set; }

    public virtual ICollection<Tag> Tags { get; set; } = new List<Tag>();
}