// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class QuestionBank
{
    public long Id { get; set; }

    public long TeacherId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Category { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<ImportedQuestionBank> ImportedQuestionBanks { get; set; } = new List<ImportedQuestionBank>();

    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();

    public virtual TeacherProfile Teacher { get; set; }
}