// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class QuestionAttachment
{
    public long Id { get; set; }

    public long QuestionId { get; set; }

    public string FileUrl { get; set; }

    public string FileType { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Question Question { get; set; }
}