// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class QuestionChoice
{
    public long Id { get; set; }

    public long QuestionId { get; set; }

    public string ChoiceText { get; set; }

    public bool IsCorrect { get; set; }

    public int Order { get; set; }

    public virtual Question Question { get; set; }
}