// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class RefreshToken
{
    public long Id { get; set; }

    public long UserId { get; set; }

    public string Token { get; set; }

    public DateTime ExpiresAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedByIp { get; set; }

    public DateTime? RevokedAt { get; set; }

    public string RevokedByIp { get; set; }

    public string ReplacedByToken { get; set; }

    public virtual User User { get; set; }
}