// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class SearchIndex
{
    public long Id { get; set; }

    public string EntityType { get; set; }

    public long EntityId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public string Tags { get; set; }

    public DateTime UpdatedAt { get; set; }
}