// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class StudentSubscription
{
    public long Id { get; set; }

    public long StudentId { get; set; }

    public long TeacherId { get; set; }

    public long PlanId { get; set; }

    public int MonthNumber { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public DateOnly AccessExpiresAt { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual SubscriptionPlan Plan { get; set; }

    public virtual StudentProfile Student { get; set; }

    public virtual TeacherProfile Teacher { get; set; }
}