// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class StudentProfile
{
    public long UserId { get; set; }

    public string Grade { get; set; }

    public string School { get; set; }

    public string ParentPhone { get; set; }

    public string ParentPhone2 { get; set; }

    public string Notes { get; set; }

    public virtual ICollection<Certificate> Certificates { get; set; } = new List<Certificate>();

    public virtual ICollection<CodingSubmission> CodingSubmissions { get; set; } = new List<CodingSubmission>();

    public virtual ICollection<CourseEnrollment> CourseEnrollments { get; set; } = new List<CourseEnrollment>();

    public virtual ICollection<ExamAttempt> ExamAttempts { get; set; } = new List<ExamAttempt>();

    public virtual ICollection<ExamResult> ExamResults { get; set; } = new List<ExamResult>();

    public virtual ICollection<HomeworkSubmission> HomeworkSubmissions { get; set; } = new List<HomeworkSubmission>();

    public virtual ICollection<LiveAttendance> LiveAttendances { get; set; } = new List<LiveAttendance>();

    public virtual ICollection<ParentNotification> ParentNotifications { get; set; } = new List<ParentNotification>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual ICollection<StudentProgress> StudentProgresses { get; set; } = new List<StudentProgress>();

    public virtual ICollection<StudentSubscription> StudentSubscriptions { get; set; } = new List<StudentSubscription>();

    public virtual User User { get; set; }
}
