// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class StudentProgress
{
    public long Id { get; set; }

    public long StudentId { get; set; }

    public long LessonId { get; set; }

    public decimal Completion { get; set; }

    public DateTime? LastViewed { get; set; }

    public int WatchTime { get; set; }

    public virtual Lesson Lesson { get; set; }

    public virtual StudentProfile Student { get; set; }
}