// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class SubscriptionPlan
{
    public long Id { get; set; }

    public long TeacherId { get; set; }

    public string Name { get; set; }

    public int MonthNumber { get; set; }

    public decimal Price { get; set; }

    public int DurationMonths { get; set; }

    public string Description { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<StudentSubscription> StudentSubscriptions { get; set; } = new List<StudentSubscription>();

    public virtual TeacherProfile Teacher { get; set; }
}