// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class SystemLog
{
    public long Id { get; set; }

    public string Level { get; set; }

    public string Message { get; set; }

    public string Source { get; set; }

    public DateTime CreatedAt { get; set; }
}