// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class TeacherSetting
{
    public long Id { get; set; }

    public long TeacherId { get; set; }

    public string NotificationSettings { get; set; }

    public string AISettings { get; set; }

    public string LiveMeetingSettings { get; set; }

    public string SubscriptionSettings { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual TeacherProfile Teacher { get; set; }
}