// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class TeacherProfile
{
    public long UserId { get; set; }

    public string Biography { get; set; }

    public string Photo { get; set; }

    public string Facebook { get; set; }

    public string YouTube { get; set; }

    public string Website { get; set; }

    public string Experience { get; set; }

    public string Specialization { get; set; }

    public bool IsVerified { get; set; }

    public DateTime? ApprovedAt { get; set; }

    public virtual ICollection<Announcement> Announcements { get; set; } = new List<Announcement>();

    public virtual ICollection<CodingChallenge> CodingChallenges { get; set; } = new List<CodingChallenge>();

    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();

    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();

    public virtual ICollection<Homework> Homeworks { get; set; } = new List<Homework>();

    public virtual ICollection<ImportedPackage> ImportedPackages { get; set; } = new List<ImportedPackage>();

    public virtual ICollection<LiveSession> LiveSessions { get; set; } = new List<LiveSession>();

    public virtual ICollection<QuestionBank> QuestionBanks { get; set; } = new List<QuestionBank>();

    public virtual ICollection<StudentSubscription> StudentSubscriptions { get; set; } = new List<StudentSubscription>();

    public virtual ICollection<SubscriptionPlan> SubscriptionPlans { get; set; } = new List<SubscriptionPlan>();

    public virtual TeacherSetting TeacherSetting { get; set; }

    public virtual User User { get; set; }
}