// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class Translation
{
    public long Id { get; set; }

    public int LanguageId { get; set; }

    public string Key { get; set; }

    public string Value { get; set; }

    public virtual Language Language { get; set; }
}