// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Domain.Entities;

public partial class UserSession
{
    public long Id { get; set; }

    public long UserId { get; set; }

    public string DeviceInfo { get; set; }

    public string IpAddress { get; set; }

    public DateTime LoginAt { get; set; }

    public DateTime? LogoutAt { get; set; }

    public bool IsActive { get; set; }

    public virtual User User { get; set; }
}