// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Platform.Domain.Entities;
using File = Platform.Domain.Entities.File;

namespace Platform.Infrastructure.Persistence.Context;

public partial class AppDbContext : DbContext
{
    public AppDbContext()
    {
    }

    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AdminProfile> AdminProfiles { get; set; }

    public virtual DbSet<AnalyticsSnapshot> AnalyticsSnapshots { get; set; }

    public virtual DbSet<Announcement> Announcements { get; set; }

    public virtual DbSet<ApiKey> ApiKeys { get; set; }

    public virtual DbSet<AuditLog> AuditLogs { get; set; }

    public virtual DbSet<BackgroundJob> BackgroundJobs { get; set; }

    public virtual DbSet<Certificate> Certificates { get; set; }

    public virtual DbSet<CodingChallenge> CodingChallenges { get; set; }

    public virtual DbSet<CodingSubmission> CodingSubmissions { get; set; }

    public virtual DbSet<Course> Courses { get; set; }

    public virtual DbSet<CourseEnrollment> CourseEnrollments { get; set; }

    public virtual DbSet<CourseModule> CourseModules { get; set; }

    public virtual DbSet<Exam> Exams { get; set; }

    public virtual DbSet<ExamAnswer> ExamAnswers { get; set; }

    public virtual DbSet<ExamAttempt> ExamAttempts { get; set; }

    public virtual DbSet<ExamQuestion> ExamQuestions { get; set; }

    public virtual DbSet<ExamResult> ExamResults { get; set; }

    public virtual DbSet<File> Files { get; set; }

    public virtual DbSet<Homework> Homeworks { get; set; }

    public virtual DbSet<HomeworkQuestion> HomeworkQuestions { get; set; }

    public virtual DbSet<HomeworkSubmission> HomeworkSubmissions { get; set; }

    public virtual DbSet<ImportLog> ImportLogs { get; set; }

    public virtual DbSet<ImportedLesson> ImportedLessons { get; set; }

    public virtual DbSet<ImportedPackage> ImportedPackages { get; set; }

    public virtual DbSet<ImportedQuestionBank> ImportedQuestionBanks { get; set; }

    public virtual DbSet<Invoice> Invoices { get; set; }

    public virtual DbSet<Language> Languages { get; set; }

    public virtual DbSet<Lesson> Lessons { get; set; }

    public virtual DbSet<LessonResource> LessonResources { get; set; }

    public virtual DbSet<LessonVideo> LessonVideos { get; set; }

    public virtual DbSet<LiveAttendance> LiveAttendances { get; set; }

    public virtual DbSet<LiveMeetingProvider> LiveMeetingProviders { get; set; }

    public virtual DbSet<LiveSession> LiveSessions { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<NotificationHistory> NotificationHistories { get; set; }

    public virtual DbSet<NotificationTemplate> NotificationTemplates { get; set; }

    public virtual DbSet<ParentNotification> ParentNotifications { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<Question> Questions { get; set; }

    public virtual DbSet<QuestionAttachment> QuestionAttachments { get; set; }

    public virtual DbSet<QuestionBank> QuestionBanks { get; set; }

    public virtual DbSet<QuestionChoice> QuestionChoices { get; set; }

    public virtual DbSet<QuestionType> QuestionTypes { get; set; }

    public virtual DbSet<RefreshToken> RefreshTokens { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<SearchIndex> SearchIndices { get; set; }

    public virtual DbSet<Setting> Settings { get; set; }

    public virtual DbSet<StudentProfile> StudentProfiles { get; set; }

    public virtual DbSet<StudentProgress> StudentProgresses { get; set; }

    public virtual DbSet<StudentSubscription> StudentSubscriptions { get; set; }

    public virtual DbSet<SubscriptionPlan> SubscriptionPlans { get; set; }

    public virtual DbSet<SystemLog> SystemLogs { get; set; }

    public virtual DbSet<Tag> Tags { get; set; }

    public virtual DbSet<TeacherProfile> TeacherProfiles { get; set; }

    public virtual DbSet<TeacherSetting> TeacherSettings { get; set; }

    public virtual DbSet<Translation> Translations { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserSession> UserSessions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AdminProfile>(entity =>
        {
            entity.HasKey(e => e.UserId);

            entity.Property(e => e.UserId).ValueGeneratedNever();
            entity.Property(e => e.AccessLevel)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("Standard");
            entity.Property(e => e.Department).HasMaxLength(100);

            entity.HasOne(d => d.User).WithOne(p => p.AdminProfile)
                .HasForeignKey<AdminProfile>(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<AnalyticsSnapshot>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => new { e.MetricName, e.RecordedAt }, "IX_AnalyticsSnapshots_Metric");

            entity.Property(e => e.Dimension).HasMaxLength(200);
            entity.Property(e => e.MetricName)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.MetricValue).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.RecordedAt).HasDefaultValueSql("NOW()");
        });

        modelBuilder.Entity<Announcement>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.CourseId, "IX_Announcements_CourseId");

            entity.HasIndex(e => e.TeacherId, "IX_Announcements_TeacherId");

            entity.Property(e => e.Body).IsRequired();
            entity.Property(e => e.PublishedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.Course).WithMany(p => p.Announcements)
                .HasForeignKey(d => d.CourseId);

            entity.HasOne(d => d.Teacher).WithMany(p => p.Announcements)
                .HasForeignKey(d => d.TeacherId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<ApiKey>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.KeyValue)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.Provider).HasMaxLength(100);
            entity.Property(e => e.Scope).HasMaxLength(200);
        });

        modelBuilder.Entity<AuditLog>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => new { e.EntityType, e.EntityId }, "IX_AuditLogs_Entity");

            entity.HasIndex(e => e.UserId, "IX_AuditLogs_UserId");

            entity.Property(e => e.Action)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.EntityType).HasMaxLength(100);
            entity.Property(e => e.IpAddress).HasMaxLength(64);

            entity.HasOne(d => d.User).WithMany(p => p.AuditLogs)
                .HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<BackgroundJob>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.Status, "IX_BackgroundJobs_Status");

            entity.Property(e => e.JobType)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.ScheduledAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Scheduled");
        });

        modelBuilder.Entity<Certificate>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.StudentId, "IX_Certificates_StudentId");

            entity.HasIndex(e => e.CertificateNumber, "UQ_Certificates_CertificateNumber").IsUnique();

            entity.Property(e => e.CertificateNumber)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.FileUrl).HasMaxLength(500);
            entity.Property(e => e.IssuedAt).HasDefaultValueSql("NOW()");

            entity.HasOne(d => d.Course).WithMany(p => p.Certificates)
                .HasForeignKey(d => d.CourseId);

            entity.HasOne(d => d.Exam).WithMany(p => p.Certificates)
                .HasForeignKey(d => d.ExamId);

            entity.HasOne(d => d.Student).WithMany(p => p.Certificates)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<CodingChallenge>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.TeacherId, "IX_CodingChallenges_TeacherId");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.Difficulty).HasMaxLength(20);
            entity.Property(e => e.Language).HasMaxLength(50);
            entity.Property(e => e.Marks).HasColumnType("decimal(6, 2)");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.Teacher).WithMany(p => p.CodingChallenges)
                .HasForeignKey(d => d.TeacherId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<CodingSubmission>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.CodingChallengeId, "IX_CodingSubmissions_ChallengeId");

            entity.HasIndex(e => e.StudentId, "IX_CodingSubmissions_StudentId");

            entity.Property(e => e.FileUrl).HasMaxLength(500);
            entity.Property(e => e.Score).HasColumnType("decimal(6, 2)");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Submitted");
            entity.Property(e => e.SubmittedAt).HasDefaultValueSql("NOW()");

            entity.HasOne(d => d.CodingChallenge).WithMany(p => p.CodingSubmissions)
                .HasForeignKey(d => d.CodingChallengeId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Student).WithMany(p => p.CodingSubmissions)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Course>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.Category, "IX_Courses_Category");

            entity.HasIndex(e => e.TeacherId, "IX_Courses_TeacherId");

            entity.Property(e => e.Category).HasMaxLength(100);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Thumbnail).HasMaxLength(500);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("NOW()");

            entity.HasOne(d => d.Teacher).WithMany(p => p.Courses)
                .HasForeignKey(d => d.TeacherId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<CourseModule>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.CourseId, "IX_CourseModules_CourseId");

            entity.HasIndex(e => new { e.CourseId, e.MonthNumber }, "UX_CourseModules_Course_Month").IsUnique();

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(150);

            entity.HasOne(d => d.Course).WithMany(p => p.CourseModules)
                .HasForeignKey(d => d.CourseId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Exam>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.CourseId, "IX_Exams_CourseId");

            entity.HasIndex(e => e.TeacherId, "IX_Exams_TeacherId");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.PassingMarks).HasColumnType("decimal(8, 2)");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.TotalMarks).HasColumnType("decimal(8, 2)");

            entity.HasOne(d => d.Course).WithMany(p => p.Exams)
                .HasForeignKey(d => d.CourseId);

            entity.HasOne(d => d.Teacher).WithMany(p => p.Exams)
                .HasForeignKey(d => d.TeacherId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<ExamAnswer>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.ExamAttemptId, "IX_ExamAnswers_Attempt");

            entity.HasIndex(e => e.QuestionId, "IX_ExamAnswers_Question");

            entity.Property(e => e.MarksObtained).HasColumnType("decimal(6, 2)");

            entity.HasOne(d => d.ExamAttempt).WithMany(p => p.ExamAnswers)
                .HasForeignKey(d => d.ExamAttemptId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Question).WithMany(p => p.ExamAnswers)
                .HasForeignKey(d => d.QuestionId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<ExamAttempt>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.ExamId, "IX_ExamAttempts_ExamId");

            entity.HasIndex(e => e.StudentId, "IX_ExamAttempts_StudentId");

            entity.Property(e => e.Score).HasColumnType("decimal(8, 2)");
            entity.Property(e => e.StartedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("InProgress");

            entity.HasOne(d => d.Exam).WithMany(p => p.ExamAttempts)
                .HasForeignKey(d => d.ExamId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Student).WithMany(p => p.ExamAttempts)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<ExamQuestion>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.ExamId, "IX_ExamQuestions_ExamId");

            entity.HasIndex(e => new { e.ExamId, e.QuestionId }, "UX_ExamQuestions_Exam_Question").IsUnique();

            entity.Property(e => e.Marks)
                .HasDefaultValue(1m)
                .HasColumnType("decimal(6, 2)");

            entity.HasOne(d => d.Exam).WithMany(p => p.ExamQuestions)
                .HasForeignKey(d => d.ExamId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Question).WithMany(p => p.ExamQuestions)
                .HasForeignKey(d => d.QuestionId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<ExamResult>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.ExamId, "IX_ExamResults_ExamId");

            entity.HasIndex(e => e.StudentId, "IX_ExamResults_StudentId");

            entity.HasIndex(e => e.ExamAttemptId, "UQ_ExamResults_ExamAttemptId").IsUnique();

            entity.Property(e => e.GeneratedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.Grade).HasMaxLength(10);
            entity.Property(e => e.Percentage).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.TotalScore).HasColumnType("decimal(8, 2)");

            entity.HasOne(d => d.ExamAttempt).WithOne(p => p.ExamResult)
                .HasForeignKey<ExamResult>(d => d.ExamAttemptId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Exam).WithMany(p => p.ExamResults)
                .HasForeignKey(d => d.ExamId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Student).WithMany(p => p.ExamResults)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<File>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => new { e.EntityType, e.EntityId }, "IX_Files_Entity");

            entity.HasIndex(e => e.UploaderId, "IX_Files_UploaderId");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.EntityType).HasMaxLength(100);
            entity.Property(e => e.FileName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.FileType).HasMaxLength(50);
            entity.Property(e => e.FileUrl)
                .IsRequired()
                .HasMaxLength(500);

            entity.HasOne(d => d.Uploader).WithMany(p => p.Files)
                .HasForeignKey(d => d.UploaderId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Homework>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.ToTable("Homework");

            entity.HasIndex(e => e.CourseId, "IX_Homework_CourseId");

            entity.HasIndex(e => e.TeacherId, "IX_Homework_TeacherId");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.TotalMarks).HasColumnType("decimal(8, 2)");

            entity.HasOne(d => d.Course).WithMany(p => p.Homeworks)
                .HasForeignKey(d => d.CourseId);

            entity.HasOne(d => d.Lesson).WithMany(p => p.Homeworks)
                .HasForeignKey(d => d.LessonId);

            entity.HasOne(d => d.Teacher).WithMany(p => p.Homeworks)
                .HasForeignKey(d => d.TeacherId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<HomeworkQuestion>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.HomeworkId, "IX_HomeworkQuestions_HomeworkId");

            entity.Property(e => e.Marks)
                .HasDefaultValue(1m)
                .HasColumnType("decimal(6, 2)");

            entity.HasOne(d => d.Homework).WithMany(p => p.HomeworkQuestions)
                .HasForeignKey(d => d.HomeworkId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Question).WithMany(p => p.HomeworkQuestions)
                .HasForeignKey(d => d.QuestionId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<HomeworkSubmission>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.HomeworkId, "IX_HomeworkSubmissions_HomeworkId");

            entity.HasIndex(e => e.StudentId, "IX_HomeworkSubmissions_StudentId");

            entity.HasIndex(e => new { e.HomeworkId, e.StudentId }, "UX_HomeworkSubmissions_HW_Student").IsUnique();

            entity.Property(e => e.FileUrl).HasMaxLength(500);
            entity.Property(e => e.Grade).HasColumnType("decimal(6, 2)");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Submitted");
            entity.Property(e => e.SubmissionType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.SubmittedAt).HasDefaultValueSql("NOW()");

            entity.HasOne(d => d.Homework).WithMany(p => p.HomeworkSubmissions)
                .HasForeignKey(d => d.HomeworkId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Student).WithMany(p => p.HomeworkSubmissions)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<ImportLog>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.ImportedPackageId, "IX_ImportLogs_PackageId");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.LogLevel)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Info");
            entity.Property(e => e.Message).IsRequired();

            entity.HasOne(d => d.ImportedPackage).WithMany(p => p.ImportLogs)
                .HasForeignKey(d => d.ImportedPackageId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<ImportedLesson>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.ImportedPackageId, "IX_ImportedLessons_PackageId");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.LessonMarkdown).IsRequired();

            entity.HasOne(d => d.ImportedPackage).WithMany(p => p.ImportedLessons)
                .HasForeignKey(d => d.ImportedPackageId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.TargetLesson).WithMany(p => p.ImportedLessons)
                .HasForeignKey(d => d.TargetLessonId);
        });

        modelBuilder.Entity<ImportedPackage>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.TeacherId, "IX_ImportedPackages_TeacherId");

            entity.Property(e => e.AIProvider).HasMaxLength(50);
            entity.Property(e => e.ImportDate).HasDefaultValueSql("NOW()");
            entity.Property(e => e.PackageVersion)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Pending");

            entity.HasOne(d => d.Teacher).WithMany(p => p.ImportedPackages)
                .HasForeignKey(d => d.TeacherId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<ImportedQuestionBank>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.ImportedPackageId, "IX_ImportedQuestionBanks_PackageId");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");

            entity.HasOne(d => d.ImportedPackage).WithMany(p => p.ImportedQuestionBanks)
                .HasForeignKey(d => d.ImportedPackageId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.TargetQuestionBank).WithMany(p => p.ImportedQuestionBanks)
                .HasForeignKey(d => d.TargetQuestionBankId);
        });

        modelBuilder.Entity<Invoice>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.PaymentId, "UQ_Invoices_PaymentId").IsUnique();

            entity.HasIndex(e => e.InvoiceNumber, "UQ_Invoices_InvoiceNumber").IsUnique();

            entity.Property(e => e.InvoiceNumber)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.IssuedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.PdfUrl).HasMaxLength(500);
            entity.Property(e => e.TaxAmount).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Payment).WithOne(p => p.Invoice)
                .HasForeignKey<Invoice>(d => d.PaymentId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Language>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.Code, "UQ_Language_Code").IsUnique();

            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Lesson>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.ModuleId, "IX_Lessons_ModuleId");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("NOW()");

            entity.HasOne(d => d.Module).WithMany(p => p.Lessons)
                .HasForeignKey(d => d.ModuleId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<LessonResource>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.LessonId, "IX_LessonResources_LessonId");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.FileName).HasMaxLength(255);
            entity.Property(e => e.FileUrl)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.ResourceType)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Lesson).WithMany(p => p.LessonResources)
                .HasForeignKey(d => d.LessonId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<LessonVideo>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.LessonId, "IX_LessonVideos_LessonId");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.Provider).HasMaxLength(50);
            entity.Property(e => e.RecordingUrl).HasMaxLength(500);
            entity.Property(e => e.Thumbnail).HasMaxLength(500);
            entity.Property(e => e.VideoUrl).HasMaxLength(500);

            entity.HasOne(d => d.Lesson).WithMany(p => p.LessonVideos)
                .HasForeignKey(d => d.LessonId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<CourseEnrollment>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => new { e.CourseId, e.StudentId }, "UX_CourseEnrollments_Course_Student").IsUnique();
            entity.HasIndex(e => e.StudentId, "IX_CourseEnrollments_StudentId");
            entity.HasIndex(e => e.Status, "IX_CourseEnrollments_Status");

            entity.Property(e => e.AccessType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.EnrolledAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30);

            entity.HasOne(d => d.Course).WithMany(p => p.CourseEnrollments)
                .HasForeignKey(d => d.CourseId)
                .OnDelete(DeleteBehavior.Cascade);

            entity.HasOne(d => d.Student).WithMany(p => p.CourseEnrollments)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.Cascade);

            entity.HasOne(d => d.Payment).WithMany(p => p.CourseEnrollments)
                .HasForeignKey(d => d.PaymentId)
                .OnDelete(DeleteBehavior.SetNull);
        });

        modelBuilder.Entity<HomeworkSubmission>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.HomeworkId, "IX_HomeworkSubmissions_HomeworkId");

            entity.HasIndex(e => e.StudentId, "IX_HomeworkSubmissions_StudentId");

            entity.HasIndex(e => new { e.HomeworkId, e.StudentId }, "UX_HomeworkSubmissions_HW_Student").IsUnique();

            entity.Property(e => e.FileUrl).HasMaxLength(500);
            entity.Property(e => e.Grade).HasColumnType("decimal(6, 2)");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Submitted");
            entity.Property(e => e.SubmissionType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.SubmittedAt).HasDefaultValueSql("NOW()");

            entity.HasOne(d => d.Homework).WithMany(p => p.HomeworkSubmissions)
                .HasForeignKey(d => d.HomeworkId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Student).WithMany(p => p.HomeworkSubmissions)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<ImportLog>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.ImportedPackageId, "IX_ImportLogs_PackageId");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.LogLevel)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Info");
            entity.Property(e => e.Message).IsRequired();

            entity.HasOne(d => d.ImportedPackage).WithMany(p => p.ImportLogs)
                .HasForeignKey(d => d.ImportedPackageId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<ImportedLesson>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.ImportedPackageId, "IX_ImportedLessons_PackageId");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.LessonMarkdown).IsRequired();

            entity.HasOne(d => d.ImportedPackage).WithMany(p => p.ImportedLessons)
                .HasForeignKey(d => d.ImportedPackageId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.TargetLesson).WithMany(p => p.ImportedLessons)
                .HasForeignKey(d => d.TargetLessonId);
        });

        modelBuilder.Entity<ImportedPackage>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.TeacherId, "IX_ImportedPackages_TeacherId");

            entity.Property(e => e.AIProvider).HasMaxLength(50);
            entity.Property(e => e.ImportDate).HasDefaultValueSql("NOW()");
            entity.Property(e => e.PackageVersion)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Pending");

            entity.HasOne(d => d.Teacher).WithMany(p => p.ImportedPackages)
                .HasForeignKey(d => d.TeacherId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<ImportedQuestionBank>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.ImportedPackageId, "IX_ImportedQuestionBanks_PackageId");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");

            entity.HasOne(d => d.ImportedPackage).WithMany(p => p.ImportedQuestionBanks)
                .HasForeignKey(d => d.ImportedPackageId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.TargetQuestionBank).WithMany(p => p.ImportedQuestionBanks)
                .HasForeignKey(d => d.TargetQuestionBankId);
        });

        modelBuilder.Entity<Invoice>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.PaymentId, "UQ_Invoices_PaymentId").IsUnique();

            entity.HasIndex(e => e.InvoiceNumber, "UQ_Invoices_InvoiceNumber").IsUnique();

            entity.Property(e => e.InvoiceNumber)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.IssuedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.PdfUrl).HasMaxLength(500);
            entity.Property(e => e.TaxAmount).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Payment).WithOne(p => p.Invoice)
                .HasForeignKey<Invoice>(d => d.PaymentId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Language>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.Code, "UQ_Language_Code").IsUnique();

            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Lesson>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.ModuleId, "IX_Lessons_ModuleId");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("NOW()");

            entity.HasOne(d => d.Module).WithMany(p => p.Lessons)
                .HasForeignKey(d => d.ModuleId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<LessonResource>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.LessonId, "IX_LessonResources_LessonId");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.FileName).HasMaxLength(255);
            entity.Property(e => e.FileUrl)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.ResourceType)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Lesson).WithMany(p => p.LessonResources)
                .HasForeignKey(d => d.LessonId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<LessonVideo>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.LessonId, "IX_LessonVideos_LessonId");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.Provider).HasMaxLength(50);
            entity.Property(e => e.RecordingUrl).HasMaxLength(500);
            entity.Property(e => e.Thumbnail).HasMaxLength(500);
            entity.Property(e => e.VideoUrl).HasMaxLength(500);

            entity.HasOne(d => d.Lesson).WithMany(p => p.LessonVideos)
                .HasForeignKey(d => d.LessonId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<LiveAttendance>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.ToTable("LiveAttendance");

            entity.HasIndex(e => e.LiveSessionId, "IX_LiveAttendance_Session");

            entity.HasIndex(e => e.StudentId, "IX_LiveAttendance_Student");

            entity.HasIndex(e => new { e.LiveSessionId, e.StudentId }, "UX_LiveAttendance_Session_Student").IsUnique();

            entity.HasOne(d => d.LiveSession).WithMany(p => p.LiveAttendances)
                .HasForeignKey(d => d.LiveSessionId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Student).WithMany(p => p.LiveAttendances)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<LiveMeetingProvider>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.Name, "UQ_LiveMeetingProvider_Name").IsUnique();

            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<LiveSession>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.CourseId, "IX_LiveSessions_CourseId");

            entity.HasIndex(e => e.StartTime, "IX_LiveSessions_StartTime");

            entity.HasIndex(e => e.TeacherId, "IX_LiveSessions_TeacherId");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.MeetingId).HasMaxLength(150);
            entity.Property(e => e.MeetingLink).HasMaxLength(500);
            entity.Property(e => e.Password).HasMaxLength(100);
            entity.Property(e => e.RecordingLink).HasMaxLength(500);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Scheduled");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.Course).WithMany(p => p.LiveSessions)
                .HasForeignKey(d => d.CourseId);

            entity.HasOne(d => d.Module).WithMany(p => p.LiveSessions)
                .HasForeignKey(d => d.ModuleId);

            entity.HasOne(d => d.Provider).WithMany(p => p.LiveSessions)
                .HasForeignKey(d => d.ProviderId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Teacher).WithMany(p => p.LiveSessions)
                .HasForeignKey(d => d.TeacherId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.IsRead, "IX_Notifications_IsRead");

            entity.HasIndex(e => e.UserId, "IX_Notifications_UserId");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Type).HasMaxLength(50);

            entity.HasOne(d => d.User).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<NotificationHistory>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.ToTable("NotificationHistory");

            entity.HasIndex(e => e.UserId, "IX_NotificationHistory_UserId");

            entity.Property(e => e.Channel)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.SentAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Sent");

            entity.HasOne(d => d.Notification).WithMany(p => p.NotificationHistories)
                .HasForeignKey(d => d.NotificationId);

            entity.HasOne(d => d.User).WithMany(p => p.NotificationHistories)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<NotificationTemplate>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.Name, "UQ_NotificationTemplate_Name").IsUnique();

            entity.Property(e => e.Body).IsRequired();
            entity.Property(e => e.Channel)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.Subject).HasMaxLength(300);
        });

        modelBuilder.Entity<ParentNotification>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.StudentId, "IX_ParentNotifications_StudentId");

            entity.Property(e => e.ParentPhone)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.ReportType)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("WeeklyReport");
            entity.Property(e => e.SentAt).HasDefaultValueSql("NOW()");

            entity.HasOne(d => d.Student).WithMany(p => p.ParentNotifications)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.StudentId, "IX_Payments_StudentId");

            entity.HasIndex(e => e.SubscriptionId, "IX_Payments_SubscriptionId");

            entity.HasIndex(e => e.TransactionId, "UQ_Payments_TransactionId").IsUnique();

            entity.Property(e => e.Amount).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.Currency)
                .IsRequired()
                .HasMaxLength(10)
                .HasDefaultValue("EGP");
            entity.Property(e => e.PaymentMethod).HasMaxLength(50);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Pending");
            entity.Property(e => e.TransactionId)
                .IsRequired()
                .HasMaxLength(150);

            entity.HasOne(d => d.Student).WithMany(p => p.Payments)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Subscription).WithMany(p => p.Payments)
                .HasForeignKey(d => d.SubscriptionId);
        });

        modelBuilder.Entity<Question>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.QuestionBankId, "IX_Questions_QuestionBankId");

            entity.HasIndex(e => e.QuestionTypeId, "IX_Questions_QuestionTypeId");

            entity.Property(e => e.BloomLevel).HasMaxLength(50);
            entity.Property(e => e.Body).IsRequired();
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.Difficulty).HasMaxLength(20);
            entity.Property(e => e.Marks)
                .HasDefaultValue(1m)
                .HasColumnType("decimal(6, 2)");
            entity.Property(e => e.Skill).HasMaxLength(150);
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("NOW()");

            entity.HasOne(d => d.QuestionBank).WithMany(p => p.Questions)
                .HasForeignKey(d => d.QuestionBankId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.QuestionType).WithMany(p => p.Questions)
                .HasForeignKey(d => d.QuestionTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasMany(d => d.Tags).WithMany(p => p.Questions)
                .UsingEntity<Dictionary<string, object>>(
                    "QuestionTag",
                    r => r.HasOne<Tag>().WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.ClientSetNull),
                    l => l.HasOne<Question>().WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.ClientSetNull),
                    j =>
                    {
                        j.HasKey("QuestionId", "TagId");
                        j.ToTable("QuestionTags");
                    });
        });

        modelBuilder.Entity<QuestionAttachment>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.QuestionId, "IX_QuestionAttachments_QuestionId");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.FileType).HasMaxLength(50);
            entity.Property(e => e.FileUrl)
                .IsRequired()
                .HasMaxLength(500);

            entity.HasOne(d => d.Question).WithMany(p => p.QuestionAttachments)
                .HasForeignKey(d => d.QuestionId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<QuestionBank>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.TeacherId, "IX_QuestionBanks_TeacherId");

            entity.Property(e => e.Category).HasMaxLength(100);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.Teacher).WithMany(p => p.QuestionBanks)
                .HasForeignKey(d => d.TeacherId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<QuestionChoice>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.QuestionId, "IX_QuestionChoices_QuestionId");

            entity.Property(e => e.ChoiceText).IsRequired();

            entity.HasOne(d => d.Question).WithMany(p => p.QuestionChoices)
                .HasForeignKey(d => d.QuestionId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<QuestionType>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.Name, "UQ_QuestionType_Name").IsUnique();

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<RefreshToken>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.UserId, "IX_RefreshTokens_UserId");

            entity.HasIndex(e => e.Token, "UX_RefreshTokens_Token").IsUnique();

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.CreatedByIp).HasMaxLength(64);
            entity.Property(e => e.ReplacedByToken).HasMaxLength(500);
            entity.Property(e => e.RevokedByIp).HasMaxLength(64);
            entity.Property(e => e.Token)
                .IsRequired()
                .HasMaxLength(500);

            entity.HasOne(d => d.User).WithMany(p => p.RefreshTokens)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.Name, "UQ_Roles_Name").IsUnique();

            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<SearchIndex>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.ToTable("SearchIndex");

            entity.HasIndex(e => new { e.EntityType, e.EntityId }, "UX_SearchIndex_Entity").IsUnique();

            entity.Property(e => e.EntityType)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Tags).HasMaxLength(500);
            entity.Property(e => e.Title).HasMaxLength(300);
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("NOW()");
        });

        modelBuilder.Entity<Setting>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.Key, "UQ_Settings_Key").IsUnique();

            entity.Property(e => e.Category).HasMaxLength(100);
            entity.Property(e => e.Description).HasMaxLength(300);
            entity.Property(e => e.Key)
                .IsRequired()
                .HasMaxLength(150);
        });

        modelBuilder.Entity<StudentProfile>(entity =>
        {
            entity.HasKey(e => e.UserId);

            entity.Property(e => e.UserId).ValueGeneratedNever();
            entity.Property(e => e.Grade).HasMaxLength(50);
            entity.Property(e => e.ParentPhone).HasMaxLength(30);
            entity.Property(e => e.ParentPhone2).HasMaxLength(30);
            entity.Property(e => e.School).HasMaxLength(150);

            entity.HasOne(d => d.User).WithOne(p => p.StudentProfile)
                .HasForeignKey<StudentProfile>(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<StudentProgress>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.ToTable("StudentProgress");

            entity.HasIndex(e => e.LessonId, "IX_StudentProgress_LessonId");

            entity.HasIndex(e => e.StudentId, "IX_StudentProgress_StudentId");

            entity.HasIndex(e => new { e.StudentId, e.LessonId }, "UX_StudentProgress_Student_Lesson").IsUnique();

            entity.Property(e => e.Completion).HasColumnType("decimal(5, 2)");

            entity.HasOne(d => d.Lesson).WithMany(p => p.StudentProgresses)
                .HasForeignKey(d => d.LessonId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Student).WithMany(p => p.StudentProgresses)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<StudentSubscription>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.AccessExpiresAt, "IX_StudentSubscriptions_AccessExpiresAt");

            entity.HasIndex(e => e.StudentId, "IX_StudentSubscriptions_StudentId");

            entity.HasIndex(e => e.TeacherId, "IX_StudentSubscriptions_TeacherId");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Active");

            entity.HasOne(d => d.Plan).WithMany(p => p.StudentSubscriptions)
                .HasForeignKey(d => d.PlanId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Student).WithMany(p => p.StudentSubscriptions)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Teacher).WithMany(p => p.StudentSubscriptions)
                .HasForeignKey(d => d.TeacherId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<SubscriptionPlan>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.TeacherId, "IX_SubscriptionPlans_TeacherId");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.DurationMonths).HasDefaultValue(1);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Teacher).WithMany(p => p.SubscriptionPlans)
                .HasForeignKey(d => d.TeacherId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<SystemLog>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => new { e.Level, e.CreatedAt }, "IX_SystemLogs_Level_CreatedAt");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.Level)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Info");
            entity.Property(e => e.Message).IsRequired();
            entity.Property(e => e.Source).HasMaxLength(150);
        });

        modelBuilder.Entity<Tag>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.Name, "UQ_Tags_Name").IsUnique();

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<TeacherProfile>(entity =>
        {
            entity.HasKey(e => e.UserId);

            entity.Property(e => e.UserId).ValueGeneratedNever();
            entity.Property(e => e.Experience).HasMaxLength(300);
            entity.Property(e => e.Facebook).HasMaxLength(300);
            entity.Property(e => e.Photo).HasMaxLength(500);
            entity.Property(e => e.Specialization).HasMaxLength(300);
            entity.Property(e => e.Website).HasMaxLength(300);
            entity.Property(e => e.YouTube).HasMaxLength(300);

            entity.HasOne(d => d.User).WithOne(p => p.TeacherProfile)
                .HasForeignKey<TeacherProfile>(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<TeacherSetting>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.TeacherId, "UQ_TeacherSetting_TeacherId").IsUnique();

            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("NOW()");

            entity.HasOne(d => d.Teacher).WithOne(p => p.TeacherSetting)
                .HasForeignKey<TeacherSetting>(d => d.TeacherId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Translation>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => new { e.LanguageId, e.Key }, "UX_Translations_Lang_Key").IsUnique();

            entity.Property(e => e.Key)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Value).IsRequired();

            entity.HasOne(d => d.Language).WithMany(p => p.Translations)
                .HasForeignKey(d => d.LanguageId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.IsActive, "IX_Users_IsActive");

            entity.HasIndex(e => e.RoleId, "IX_Users_RoleId");

            entity.HasIndex(e => e.Email, "UQ_Users_Email").IsUnique();

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(256);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.Phone).HasMaxLength(30);
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("NOW()");

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<UserSession>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.HasIndex(e => e.UserId, "IX_UserSessions_UserId");

            entity.Property(e => e.DeviceInfo).HasMaxLength(300);
            entity.Property(e => e.IpAddress).HasMaxLength(64);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.LoginAt).HasDefaultValueSql("NOW()");

            entity.HasOne(d => d.User).WithMany(p => p.UserSessions)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
